// Programmatic migration of the existing hard-coded content into the CMS data model.
// The same dataset is used for:
//   1. supabase/seed.sql (generated by scripts/cms/generate-seed-sql.mjs)
//   2. the public site's fallback content when Supabase is not configured
//   3. the in-memory mock backend used for local dashboard development
import { SITE_CONTENT } from '../data/content-data.js';
import { SITE_CONTENT_AR } from '../data/content-ar.js';
import { SERVICE_DETAILS } from '../data/service-details.js';
import { WORK_ITEMS } from '../data/work-data.js';
import { CLIENTS } from '../data/clients-data.js';
import { HOME_SECTIONS, SERVICE_TEMPLATE_SECTION } from './defaults/sections.js';

// Deterministic UUID-shaped ids so seeded rows keep stable identities everywhere.
export function seedId(name) {
  let h1 = 1779033703, h2 = 3144134277, h3 = 1013904242, h4 = 2773480762;
  for (let i = 0; i < name.length; i++) {
    const k = name.charCodeAt(i);
    h1 = h2 ^ Math.imul(h1 ^ k, 597399067);
    h2 = h3 ^ Math.imul(h2 ^ k, 2869860233);
    h3 = h4 ^ Math.imul(h3 ^ k, 951274213);
    h4 = h1 ^ Math.imul(h4 ^ k, 2716044179);
  }
  const hex = [h1, h2, h3, h4].map((h) => (h >>> 0).toString(16).padStart(8, '0')).join('');
  return `${hex.slice(0, 8)}-${hex.slice(8, 12)}-4${hex.slice(13, 16)}-a${hex.slice(17, 20)}-${hex.slice(20, 32)}`;
}

const TIMESTAMP = '2026-09-26T00:00:00.000Z';
const stamp = (row) => ({ ...row, created_at: TIMESTAMP, updated_at: TIMESTAMP });

const settings = stamp({
  id: 1,
  site_name: '5CHICKS',
  logo_url: 'assets/identity/logo.webp',
  favicon_url: 'assets/identity/symbol.webp',
  phone: '+201004066939',
  phone_display: '+20 100 406 6939',
  email: '',
  whatsapp_number: '201004066939',
  whatsapp_message_en: '',
  whatsapp_message_ar: '',
  whatsapp_label_en: 'Chat with us',
  whatsapp_label_ar: 'كلّمنا على واتساب',
  whatsapp_aria_en: 'Chat with us on WhatsApp',
  whatsapp_aria_ar: 'كلّمنا على واتساب',
  social_links: [],
  default_seo_title_en: '5CHICKS — Small chicks. Big energy.',
  default_seo_title_ar: '5CHICKS — حجمنا صغير. إبداعنا كبير.',
  default_seo_description_en:
    '5CHICKS is a creative house powered by five creative forces. Branding, digital marketing, software, media production and visual art.',
  default_seo_description_ar:
    '5CHICKS بيت إبداعي يجمع الهوية التجارية والتسويق الرقمي والبرمجيات والإنتاج الإعلامي والفنون البصرية.',
  og_image_url: 'assets/brand-logo.png',
  og_image_alt_en: '5CHICKS Agency logo',
  og_image_alt_ar: 'شعار وكالة 5CHICKS'
});

const pages = [
  {
    slug: 'home',
    title_en: 'Home',
    title_ar: 'الرئيسية',
    seo_title_en: settings.default_seo_title_en,
    seo_title_ar: settings.default_seo_title_ar,
    seo_description_en: settings.default_seo_description_en,
    seo_description_ar: settings.default_seo_description_ar
  },
  {
    slug: 'services',
    title_en: 'Services',
    title_ar: 'خدماتنا',
    seo_title_en: 'Services — 5CHICKS Creative House',
    seo_title_ar: 'خدماتنا — 5CHICKS',
    seo_description_en:
      'Five connected creative services from 5CHICKS: digital marketing, branding, software, media production and visual art.',
    seo_description_ar:
      'خمس خدمات إبداعية متكاملة من 5CHICKS: التسويق الرقمي والهوية التجارية والبرمجيات والإنتاج الإعلامي والفنون البصرية.'
  },
  {
    slug: 'portfolio',
    title_en: 'Portfolio',
    title_ar: 'البورتفوليو',
    seo_title_en: 'Portfolio — 5CHICKS Creative House',
    seo_title_ar: 'البورتفوليو — 5CHICKS',
    seo_description_en:
      'Explore the 5CHICKS company portfolio, selected projects and our reels, films and sketches.',
    seo_description_ar:
      'اتعرّف على بورتفوليو شركة 5CHICKS ومختارات من أعمالنا والريلز والأفلام والسكتشات.'
  },
  {
    slug: 'contact',
    title_en: 'Contact',
    title_ar: 'تواصل معانا',
    seo_title_en: 'Contact — 5CHICKS Creative House',
    seo_title_ar: 'تواصل معانا — 5CHICKS',
    seo_description_en: 'Start your next project with 5CHICKS. Call us or chat on WhatsApp: +20 100 406 6939.',
    seo_description_ar: 'ابدأ مشروعك الجاي مع 5CHICKS. كلّمنا أو ابعتلنا على واتساب: ‎+20 100 406 6939.'
  }
].map((page) => stamp({ id: seedId('page:' + page.slug), published: true, og_image_url: '', ...page }));

const sections = [
  ...HOME_SECTIONS.map((section, index) => ({ ...section, page_slug: 'home', sort_order: index })),
  { ...SERVICE_TEMPLATE_SECTION, page_slug: 'services', sort_order: 0 }
].map((section) =>
  stamp({ id: seedId(`section:${section.page_slug}:${section.key}`), enabled: true, ...section })
);

// Services: base fields + Arabic overrides + detail-page content as unlimited child items.
const services = SITE_CONTENT.services.map((service, index) => {
  const ar = SITE_CONTENT_AR.services[service.id] || {};
  const details = SERVICE_DETAILS[service.id];
  const serviceId = seedId('service:' + service.id);
  const items = [];
  const push = (kind, list, map) =>
    list.forEach((entry, i) =>
      items.push(stamp({ id: seedId(`service-item:${service.id}:${kind}:${i}`), service_id: serviceId, kind, sort_order: i, ...map(entry, i) }))
    );
  push('deliverable', service.deliverables, (title, i) => ({
    title_en: title,
    title_ar: ar.deliverables?.[i] || title,
    body_en: details.en.offers[i]?.[1] || '',
    body_ar: details.ar.offers[i]?.[1] || ''
  }));
  push('process', details.en.process, ([title, body], i) => ({
    title_en: title, body_en: body, title_ar: details.ar.process[i][0], body_ar: details.ar.process[i][1]
  }));
  push('value', details.en.value, ([title, body], i) => ({
    title_en: title, body_en: body, title_ar: details.ar.value[i][0], body_ar: details.ar.value[i][1]
  }));
  push('faq', details.en.faq, ([title, body], i) => ({
    title_en: title, body_en: body, title_ar: details.ar.faq[i][0], body_ar: details.ar.faq[i][1]
  }));
  return stamp({
    id: serviceId,
    slug: service.id,
    sort_order: index,
    published: true,
    name_en: service.title,
    name_ar: ar.title || service.title,
    tagline_en: service.tagline,
    tagline_ar: ar.tagline || service.tagline,
    description_en: service.description,
    description_ar: ar.description || service.description,
    overview_en: details.en.overview.join('\n\n'),
    overview_ar: details.ar.overview.join('\n\n'),
    color: service.color,
    icon_url: service.icon,
    hero_image_url: service.image || '',
    work_link: service.workLink || '',
    whatsapp_message_en: details.whatsapp.en,
    whatsapp_message_ar: details.whatsapp.ar,
    seo_title_en: details.seo.en.title,
    seo_title_ar: details.seo.ar.title,
    seo_description_en: details.seo.en.description,
    seo_description_ar: details.seo.ar.description,
    og_image_url: '',
    items
  });
});

// Work collections → sliders; every video item → a slide.
const COLLECTIONS = [
  { key: 'reels', title: ['REELS', 'ريلز'], nav: ['Reels', 'ريلز'], text: ['Short-form stories. Made for the moment.', 'حكايات قصيرة. معمولة للحظة.'] },
  { key: 'films', title: ['FILMS', 'أفلام'], nav: ['Films', 'أفلام'], text: ['Cinematic thinking. Stories worth staying for.', 'رؤية سينمائية. وحكايات تستاهل وقتك.'] },
  { key: 'sketches', title: ['SKETCHES', 'سكتشات'], nav: ['Sketches', 'سكتشات'], text: ['Characters, scenes and ideas with personality.', 'شخصيات ومشاهد وأفكار ليها روح.'] }
];
const sliders = COLLECTIONS.map((collection, index) => {
  const sliderId = seedId('slider:' + collection.key);
  return stamp({
    id: sliderId,
    key: collection.key,
    sort_order: index,
    enabled: true,
    title_en: collection.title[0],
    title_ar: collection.title[1],
    nav_label_en: collection.nav[0],
    nav_label_ar: collection.nav[1],
    description_en: collection.text[0],
    description_ar: collection.text[1],
    slides: WORK_ITEMS.filter((item) => item.category === collection.key && item.src).map((item, i) =>
      stamp({
        id: seedId(`slide:${collection.key}:${item.src}`),
        slider_id: sliderId,
        sort_order: i,
        enabled: true,
        title_en: item.title,
        title_ar: item.titleAr || item.title,
        description_en: '',
        description_ar: '',
        label_en: item.label || collection.key.toUpperCase(),
        label_ar: item.labelAr || item.label || collection.key.toUpperCase(),
        video_url: item.src,
        image_url: '',
        poster_url: item.poster || '',
        cta_label_en: '',
        cta_label_ar: '',
        cta_url: ''
      })
    )
  });
});

const clients = CLIENTS.filter((client) => client.name && client.logo).map((client, index) =>
  stamp({
    id: seedId('client:' + client.logo),
    sort_order: index,
    enabled: true,
    name_en: client.name,
    name_ar: client.nameAr || client.name,
    logo_url: client.logo,
    url: '',
    theme: client.theme || 'light'
  })
);

// The current site has no standalone portfolio projects (every service's `projects` array is
// empty), so none are invented here. Projects are added from the dashboard.
const projects = [];

export const SEED = { settings, pages, sections, services, sliders, clients, projects };
